name: .NET Core

on:
  milestone:
    branches: [ master ]     
    types: [closed]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Publish NuGet
      uses: rohith/publish-nuget@v2.2.0
      with:
        PROJECT_FILE_PATH: ./Wndrr.Mjml.CSharp/Wndrr.Mjml.CSharp.csproj
        NUGET_KEY: ${{ secrets.NUGET_API_KEY }}
